image: registry.sweetspotmotion.com:4567/ops/kube-deploy:stable

variables:
  KUBE_DOMAIN: svc.sweetspotmotion.com
  REGISTRY: gitlab-registry
  TIER: web
  PORT_NAME: web
  HEALTH_CHECK_PATH: /
  HEALTH_CHECK_DELAY: 15
  HEALTH_CHECK_TIMEOUT: 15
  READY_CHECK_PATH: /
  READY_CHECK_DELAY: 5
  READY_CHECK_TIMEOUT: 3
  SERVICE_PATH: /
  SPEC_TYPE: LoadBalancer
  TLS_ENABLE: "true"
  INGRESS_CLASS: nodejs
  CPORT: 80
  EPORT: 80
  SPORT: 80

stages:
  - build
  - staging
  
build:
  stage: build
  script:
    - command build
  only:
    - branches

staging:
  stage: staging
  variables:
    KUBE_NAMESPACE: default
    REPLICAS: 1
    HPA_MIN_REPLICAS: 1
    HPA_MAX_REPLICAS: 10
    HPA_TARGET_CPU: 50
    TRACK: stg
    MEM_REQ: 100Mi
    MEM_LIMIT: 400Mi
    CPU_REQ: 100m
    CPU_LIMIT: 500m
  script:
    - command deploy
  environment:
    name: $CI_PROJECT_NAME-stg
    url: http://$CI_ENVIRONMENT_NAME.$KUBE_DOMAIN
  only:
    - stg